version: '3'
services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE:-hello}
      MYSQL_USER: ${MYSQL_USER:-hello}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-hello}
    ports:
      - 3306:3306
    volumes:
      - idealcardata:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    cap_add:
      - SYS_NICE
volumes:
  idealcardata:
